Repository fga-eps-mds/2022-2-CAPJu-Doc, pull requests merged in 2023-02, with the labels that each got.

#169 Docs/168 nova paleta de cores
  _sidebar.md
  assets/css/custom.css
  assets/images/GuiaDeIdentidadeVisual/1.png
  assets/images/GuiaDeIdentidadeVisual/2.png
  assets/images/GuiaDeIdentidadeVisual/3.png
  assets/images/GuiaDeIdentidadeVisual/4.png
  assets/images/GuiaDeIdentidadeVisual/5.png
  pages/documentation/visualidentity.md
Labels: documentation, DOCS

#180 179-Atualização da pagina de protótipos
  pages/prototypes.md
Labels: DOCS

#182 181-Atualização da pagina de treinamentos
  pages/trainning.md
Labels: DOCS

#167 Roteiro de instalção do usuário
  _sidebar.md
  pages/documentation/manual.md
Labels: DOCS

#178 Atualização de riscos
  pages/planning/risks.md
Labels: documentation, DOCS

#187 Atualização pareamentos
  assets/css/custom.css
  pages/team_control/pair_programming.md
Labels: DOCS

#191 Docs/142 reescrever custos
  pages/planning/costs.md
Labels: HOTFIX, DOCS

#192 Docs/186 arrumar arquitetura
  pages/documentation/architecture.md
  pages/documentation/assets/DER.png
  pages/documentation/assets/DLD.png
Labels: documentation, DOCS
